// This file was autogenerated by closure-primitives/depswriter.py.
// Please do not edit.
goog.addDependency('../closure-primitives/base.js', ['goog'], []);
goog.addDependency('../define/typedarray/hybrid.js', ['USE_TYPEDARRAY'], []);
goog.addDependency('../define/typedarray/use.js', ['USE_TYPEDARRAY'], []);
goog.addDependency('../src/CanvasTool/pngencoder.js', ['CanvasTool.PngEncoder'], ['Zlib.CRC32', 'Zlib.Deflate']);
goog.addDependency('../vendor/zlib.js/closure-primitives/base.js', ['goog'], []);
goog.addDependency('../vendor/zlib.js/define/typedarray/hybrid.js', ['USE_TYPEDARRAY'], []);
goog.addDependency('../vendor/zlib.js/define/typedarray/use.js', ['USE_TYPEDARRAY'], []);
goog.addDependency('../vendor/zlib.js/src/adler32.js', ['Zlib.Adler32'], []);
goog.addDependency('../vendor/zlib.js/src/bitstream.js', ['Zlib.BitStream'], []);
goog.addDependency('../vendor/zlib.js/src/crc32.js', ['Zlib.CRC32'], []);
goog.addDependency('../vendor/zlib.js/src/deflate.js', ['Zlib.Deflate'], ['Zlib.Adler32', 'Zlib.RawDeflate']);
goog.addDependency('../vendor/zlib.js/src/gunzip.js', ['Zlib.Gunzip'], ['Zlib.CRC32', 'Zlib.GunzipMember', 'Zlib.Gzip', 'Zlib.RawInflate']);
goog.addDependency('../vendor/zlib.js/src/gzip.js', ['Zlib.Gzip'], ['Zlib.CRC32', 'Zlib.RawDeflate']);
goog.addDependency('../vendor/zlib.js/src/gzip_member.js', ['Zlib.GunzipMember'], []);
goog.addDependency('../vendor/zlib.js/src/heap.js', ['Zlib.Heap'], []);
goog.addDependency('../vendor/zlib.js/src/huffman.js', ['Zlib.Huffman'], []);
goog.addDependency('../vendor/zlib.js/src/inflate.js', ['Zlib.Inflate'], ['Zlib.Adler32', 'Zlib.RawInflate']);
goog.addDependency('../vendor/zlib.js/src/inflate_stream.js', ['Zlib.InflateStream'], ['Zlib.RawInflateStream']);
goog.addDependency('../vendor/zlib.js/src/rawdeflate.js', ['Zlib.RawDeflate'], ['Zlib.BitStream', 'Zlib.Heap']);
goog.addDependency('../vendor/zlib.js/src/rawinflate.js', ['Zlib.RawInflate'], ['Zlib.Huffman']);
goog.addDependency('../vendor/zlib.js/src/rawinflate_stream.js', ['Zlib.RawInflateStream'], ['Zlib.Huffman']);
goog.addDependency('../vendor/zlib.js/src/util.js', ['Zlib.Util'], []);
goog.addDependency('../vendor/zlib.js/src/zlib.js', ['Zlib'], ['Zlib.Deflate', 'Zlib.Inflate']);
